services:

  app:
    build:
      context: ./docker-laravel
      dockerfile: docker/php/Dockerfile
    container_name: simple_crud
    volumes:
      - ./simple-crud:/var/www
    working_dir: /var/www
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./simple-crud:/var/www
      - ./docker-laravel/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel_node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./simple-crud:/var/www
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simple_crud_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data: